name: CI

on:
  pull_request:

  push:
    branches:
      - main

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'development test'
      BUNDLE_WITH: 'lint'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true # 'bundle install' and cache gems
      - name: Rubocop
        run: bundle exec rubocop --format progress
  build:
    needs: [linting]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt install libcurl4-openssl-dev
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and then cache gems
    - name: Test
      run: bundle exec rake
