name: CI

on:
  pull_request:

  push:
    branches:
      - master

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.4', '2.5', '2.6', '2.7']

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev

    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash
        
    - name: Set up Ruby
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install ${{ matrix.ruby }} --disable-binary
        rvm --default use ${{ matrix.ruby }}

    - name: Build
      run: |
        source $HOME/.rvm/scripts/rvm
        sudo apt-get install libcurl4-openssl-dev
        gem install bundler -v '<2'
        bundle install --jobs 4 --retry 3

    - name: Setup Code Climate
      if: matrix.ruby == '2.6'
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Test
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rake

    - name: Run Code Climate Test Reporter
      if: success() && matrix.ruby == '2.6'
      run: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      continue-on-error: true
